### ISSUE TITLE
Unclear as to "what can't the browser do"?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-annotation#9]
From a browser vendor's perspective, it would be good if the document was more clear as to how, for example, `<a>` elements, custom data, and fragment identifiers are insufficient in achieving each of the use cases. It would also be good if the document could show how applications are hacking around the limitations in browsers today.  

Adding the information above would go a long way to adding more credibility towards showing that this is a real problem and limitation in the Web platform. 

I would urge you to take a look at http://usecases.responsiveimages.org/, which was used to convince browser vendors that there were serious limitations in the platform with regards to images. Something similar would go a long way with respect to annotations... it will also make it more clear as to whether this needs an actual in-browser solution or if this is just going to be a data format (e.g., something build on top of JSON-LD, XML, or whatever).

**Comment by azaroth42** [comment]
Hi Marcos,
I don't disagree at all :) I'd like to note that this document is only intended as input from the Digital Publishing Interest Group to the Web Annotation Working Group's work.  It is not output from the Working Group, which would definitely benefit from exactly what you're advocating.

The WAWG has several deliverables that span your options, and hence the potential confusion.  There is the data model and format, the transport protocol to move annotations in that format between client and server, and the browser side requirements for building annotation clients that quickly and easily generate that data.

**Comment by marcoscaceres** [comment]
@azaroth42 thanks for the clarification.
